name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies & Test
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        cd backend
        echo '{"port":8888,"hook-secret":"","name":"","discord-hook":"","admins":["kenny2scratch"]}' > config.json
        python3 . --debug &
        sleep 3
        python3 ../tests.py
